services:
    _defaults:
        tags: ['nelmio_alice.faker.provider']
        autowire: true
        public: true
        bind:
            $keywordRepository: '@swp.repository.keyword'
            $keywordFactory: '@swp.factory.keyword'

    SWP\Bundle\FixturesBundle\Faker\Provider\:
        resource: '../../Faker/Provider/*'

    SWP\Bundle\FixturesBundle\Faker\Provider\RouteProvider:
        arguments:
                - '@swp.provider.route'
        tags:
            - { name: nelmio_alice.faker.provider }
